# Default values for BTFHub online.

name: btfhub-online
image: us.gcr.io/seekret/btfhub:2.0.0

ingress:
  enabled: true
  name: "{{ .Values.name }}-ingress"
  secret_name: "{{ .Values.name }}-tls"
  static_ip_name: "{{ .Values.name }}-ip"
  host:
  domain:
  tls:
    cert:
    key:

resources:
  requests:
    memory: 1000Mi
    cpu: 1000m
  limits:
    memory: 1500Mi
    cpu: 1500m

horizontal_scaling:
  min_pods: 1
  max_pods: 10
  cpu_utilization: 50

arguments:
  bucket_name:
  tools_directory: /app/tools
  port: 80
  disable_metrics_handler: false

  gcp_bucket:
    enabled: true
    service_account_name: gcp-bucket-service-account
    service_account_content:
