apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /monitoring/metrics
        prometheus.io/port: {{ .Values.arguments.port | quote }}
      labels:
        app: {{ .Values.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: BUCKET_NAME
              value: {{ required "A bucket name is required!" .Values.arguments.bucket_name | quote }}
            - name: TOOLS_DIR
              value: {{ .Values.arguments.tools_directory | quote }}
            - name: PORT
              value: {{ .Values.arguments.port | quote }}
            {{- if .Values.arguments.gcp_bucket.enabled }}
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/service-account.json"
            {{- end }}
            - name: NO_MONITORING
              value: {{ .Values.arguments.disable_metrics_handler | quote }}
          {{- if .Values.arguments.gcp_bucket.enabled }}
          volumeMounts:
            - mountPath: /var/run/secret/cloud.google.com
              name: {{ .Values.arguments.gcp_bucket.service_account_name }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.arguments.port }}
          livenessProbe:
            httpGet:
              path: /monitoring/health
              port: {{ .Values.arguments.port }}
            initialDelaySeconds: 3
            failureThreshold: 40
            periodSeconds: 3
      {{- if .Values.arguments.gcp_bucket.enabled }}
      volumes:
        - name: {{ .Values.arguments.gcp_bucket.service_account_name }}
          secret:
            secretName: {{ .Values.arguments.gcp_bucket.service_account_name }}
      {{- end }}
