{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.ingress.name . }}
  annotations:
    konghq.com/protocols: https
    konghq.com/https-redirect-status-code: "308"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.domain | quote }}
      secretName: {{ tpl .Values.ingress.secret_name . }}
  ingressClassName: kong
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: {{ .Values.arguments.port }}
{{- end }}
