{{- if .Values.arguments.gcp_bucket.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arguments.gcp_bucket.service_account_name }}
type: Opaque
data:
  service-account.json: {{ required "A service account is required!" .Values.arguments.gcp_bucket.service_account_content | b64enc }}
---
{{- end }}
