{{- if .Values.arguments.gcp_bucket.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arguments.gcp_bucket.service_account_name }}
type: Opaque
data:
  service-account.json: {{ required "A service account is required!" .Values.arguments.gcp_bucket.service_account_content | b64enc }}
---
{{- end }}
{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.ingress.secret_name . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A tls cert is required!" .Values.ingress.tls.cert | b64enc }}
  tls.key: {{ required "A tls key is required!" .Values.ingress.tls.key | b64enc }}
---
{{- end }}
