apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.arguments.port }}
      protocol: TCP
      targetPort: {{ .Values.arguments.port }}
  selector:
    app: {{ .Values.name }}
