name: Update BTFs
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro: [ ubuntu, debian, centos, amazon, fedora ]

    steps:
      - name: Fetch code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo add-apt-repository -y ppa:rafaeldtinoco/dwarves
          sudo apt-get update
          sudo apt-get install -y dwarves lynx sqlite3 axel

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: seekret
          service_account_key: ${{ secrets.PROD_GCR_SA_KEY }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Download
        run: |
          ./tools/update_${{ matrix.distro }}.sh
